pluralnoun1 = input("Give me a plural noun. ")
adj1 = input("Give me an adjective. ")
pluralnoun2 = input("Give me a plural noun. ")
verbing1 = input("Give me a verb ending in ing. ")
pluralnoun3 = input("Give me a plural noun. ")
adj2 = input("Give me an adjective. ")
verb2 = input("Give me a verb. ")
noun3 = input("Give me a noun. ")
verb3 = input("Give me a verb. ")
verb4 = input("Give me a verb. ")
bodypart1 = input("Give me a body part. ")

print("High school was filled with ups and downs but the hardest part was cutting off %s. " % pluralnoun1)
print("The %s %s were always %s with my %s. " % (adj1, pluralnoun2, verbing1, pluralnoun3))
print("%s friends tried to warn me about people who %s. " % (adj2, verb2))
print("My favorite %s is the one that %s. " % (noun3, verb3))
print("Overall, I know I shouldn't %s but if I don't my %s hurts." % (verb4, bodypart1))